### ISSUE TITLE
Replace label transitions with CSS transformations

### ISSUE THREAD

**Issue by matchai** [ArunMichaelDsouza/picla#1]
Animating bottom on a CSS element [triggers a repaint and compositing](https://csstriggers.com/bottom).
This negatively affects page performance and drops transitions below [the ideal 60 fps](http://www.html5rocks.com/en/tutorials/speed/high-performance-animations/).

Instead of `.css("bottom","-40%")`, using `.css("transform","translateY(-40%)")` would use the GPU for animating the element.

**Comment by ArunMichaelDsouza** [comment]
Great tip @matchai. This has been fixed in the latest version - [v0.8.1](https://github.com/ArunMichaelDsouza/picla/commit/e48f4fa94612b674bea8fb721c54b06b9207c5b0)
